### ISSUE TITLE
Tron Event Storage Permanence and Immutability on Main-Net and Shasta Test-Net

### ISSUE THREAD

**Issue by BlockChainBobC** [tronprotocol/documentation-en#45] opened 2020-10-21 06:14 UTC
I have been developing a smart Contract on Shasta Test-net for a few weeks. The contract has many custom Events that I emit to track details about what is happening. I then use JavaScript to retrieve a Log of the events to display to users of the contract.

I have noticed that sometimes after a few days the events disappear. There does not seem to be a set amount of time, Sometimes it takes days other times weeks for events to disappear from the contracts events storage....

The issue I have is this... I have read through all the documentation, and asked in both the Tron developers discord and telegram to get an answer to this question. Are events stored when emitted by a contract stored permanently on Main-net or not? On Shasta Test-net they are clearly NOT permanently stored. I wonder if this is just to save storage on Test-net, but on Main-net are Events stored permanently?

On Ethereum, Events are stored permanently, so I figured Tron and the TVM being forked from the EVM would also store Events that a contract emits in an immutable permanent fashion as well... Can someone please clarify and add to the documentation details about the length of time, or blocks that Events are stored both on Test-net and on Main-net.

**Comment by duc811997** [comment] 2020-11-12 21:35
Duplicate of #

**Comment by duc811997** [comment] 2020-11-12 21:37
> Duplicate of #45 duccum1997
> [wallet.txt](https://github.com/tronprotocol/documentation-en/files/5533421/wallet.txt)

**Comment by voanhcung** [comment] 2021-01-22 07:43
TLyqzVGLV1srkB7dToTAEqgDSfPtXRJZYH``

**Comment by Benson0224** [comment] 2021-06-23 07:06
Please check the event-related introduction from here: https://developers.tron.network/docs/vm-event
you can also use trongrid EVENT service if you did not want to deploy your own EVENT service. here is the trongrid event guide: https://developers.tron.network/reference#events-1

**Closed by Benson0224** 2021-06-23 07:06 UTC
